### ISSUE TITLE
Error On using SyncUsers();

### ISSUE THREAD

**Issue by ayndev** [Kandy-IO/kandy-laravel#5]
It seems that the response of the get users request to the kandy API does not contain user_password for the users.

and in syncUsers():
$model->password = $kandyUser->user_password;

Also for the user.type

**Comment by khoadp** [comment]
@ayndev Thanks for reporting the issue! We are looking into this and will get back to you.

**Comment by khoadp** [comment]
@ayndev, we have fixed the issue in the new releases. Please check them out:

https://github.com/Kandy-IO/kandy-laravel/releases

**Comment by ayndev** [comment]
Ok. I'll check this up. Thanks
