### ISSUE TITLE
Nothing to publish for tag [public].

### ISSUE THREAD

**Issue by bonjinjp** [Kandy-IO/kandy-laravel#6]
I set in accordance with the contents of the "Configuration".
I have entered this...

`php artisan vendor:publish --force --provider=Kodeplus\Kandylaravel\KandylaravelServiceProvider --tag=public`

but , It appears .

> Nothing to publish for tag [public].

How can we resolve this error ?

**Comment by bonjinjp** [comment]
I was solved on its own .
"provider" requires quotation .

**Comment by kodeplusdev** [comment]
@bonjinjp yes, maybe that's OS related. I was running it on Windows. Thanks for checking!
